import { useState } from "react";
import { ArrowUpRight, Check, ChevronDown, MessageCircle, Phone, CalendarDays } from "lucide-react";
import { useTranslation } from "@/hooks/useTranslation";

const QubeSightEditorialHome = () => {
  const { language } = useTranslation();
  const [channel, setChannel] = useState("WhatsApp");
  const [open, setOpen] = useState(0);
  const es = language === "es";
  const copy = es ? {
    nav:["Producto","Soluciones","Cómo funciona"], eyebrow:"AGENTES IA PARA NEGOCIOS QUE CRECEN", hero:["Tus clientes","no esperan.","Tu IA tampoco debería."], lead:"QubeSight construye agentes IA de chat y voz que responden, califican y agendan — las 24 horas.", demo:"Prueba la demostración", contact:"Hablar con un experto", problem:"Cada mensaje sin respuesta es un cliente que elige a alguien más.", problemCopy:"QubeSight cierra la distancia entre “me interesa” y una conversación que avanza. Tu equipo gana un copiloto que sabe qué decir y cuándo actuar.", film:["Una pregunta.","Una respuesta completa.","Mientras tu cliente escribe, QubeSight entiende la intención, encuentra disponibilidad y hace que el siguiente paso ocurra."], products:[["Chat Agents","WhatsApp, Instagram, Facebook y web. Respuestas, leads y agenda en un mismo flujo."],["Voice Agents","Llamadas 24/7, preguntas frecuentes, calificación y citas sin dejar a nadie en espera."],["AI Suite","Chat, voz, CRM y agenda compartidos para una operación que nunca pierde contexto."]], industries:["Clínicas dentales","Bienes raíces","Restaurantes","Belleza y bienestar","Servicios profesionales"], how:["Escucha","Entiende","Convierte"], faq:[["¿Necesito conocimientos técnicos?","No. Configuramos el agente, los canales, las FAQs y las reglas de atención contigo."],["¿La IA reemplaza a mi equipo?","No. QubeSight atiende lo repetitivo para que tu equipo se concentre en ventas, criterio y relaciones."],["¿Cuánto tarda la implementación?","La mayoría de negocios puede estar activo en menos de 48 horas."]], final:"Tu próximo cliente ya está esperando." } : {
    nav:["Product","Solutions","How it works"], eyebrow:"AI AGENTS FOR GROWING BUSINESSES", hero:["Your customers","won’t wait.","Your AI shouldn’t either."], lead:"QubeSight builds AI chat and voice agents that respond, qualify, and schedule — around the clock.", demo:"Try the demo", contact:"Talk to an expert", problem:"Every unanswered message is a customer choosing someone else.", problemCopy:"QubeSight closes the gap between “I’m interested” and a conversation that moves forward. Your team gets a copilot that knows what to say and when to act.", film:["One question.","One complete response.","While your customer writes, QubeSight understands intent, finds availability, and makes the next step happen."], products:[["Chat Agents","WhatsApp, Instagram, Facebook, and web. Answers, leads, and booking in one flow."],["Voice Agents","24/7 calls, FAQs, qualification, and appointments without putting anyone on hold."],["AI Suite","Shared chat, voice, CRM, and calendar for an operation that never loses context."]], industries:["Dental clinics","Real estate","Restaurants","Beauty & wellness","Professional services"], how:["Listens","Understands","Converts"], faq:[["Do I need technical knowledge?","No. We configure the agent, channels, FAQs, and service rules with you."],["Does AI replace my team?","No. QubeSight handles repetitive work so your team focuses on sales, judgment, and relationships."],["How long does implementation take?","Most businesses can be live in under 48 hours."]], final:"Your next customer is already waiting." };
  const chats:Record<string,string[]>={WhatsApp:["¿Tienen disponibilidad el jueves?","Sí. Tengo 2:30 PM y 4:00 PM. ¿Cuál te funciona?","2:30 por favor","Listo. Tu cita está confirmada."],Voz:["Gracias por llamar a Bright Dental.","Necesito una limpieza esta semana.","Puedo ayudarte. ¿Jueves por la tarde?","Perfecto. Quedas agendado a las 2:30 PM."],Web:["¿Puedo pedir una cotización?","Claro. Te haré unas preguntas rápidas.","Excelente, adelante.","Primero: ¿qué proyecto tienes en mente?"]};
  const labels=es?["WhatsApp","Voz","Web"]:["WhatsApp","Voice","Web"];
  const active=channel==="Voice"?"Voz":channel;
  return <main className="bg-[#f4f4f0] text-[#071120] selection:bg-[#2864ff] selection:text-white">
    <nav className="sticky top-0 z-50 flex h-[76px] items-center justify-between border-b border-[#071120]/15 bg-[#f4f4f0]/90 px-[4.5vw] backdrop-blur-xl"><a href="#top" className="text-[22px] font-black tracking-[-.09em]">qube<span className="text-[#2864ff]">•</span>sight</a><div className="hidden gap-8 text-[13px] md:flex">{copy.nav.map((x,i)=><a key={x} href={["#product","#solutions","#process"][i]}>{x}</a>)}</div><a href="#contact" className="text-[13px] font-bold">{copy.contact} <ArrowUpRight className="inline h-4 w-4 text-[#2864ff]"/></a></nav>
    <section id="top" className="relative flex min-h-[calc(100vh-76px)] flex-col justify-between overflow-hidden px-[4.5vw] py-[9vh]"><div className="relative z-10 text-[10px] font-bold tracking-[.16em]"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#2864ff]"/>{copy.eyebrow}</div><h1 className="relative z-10 my-10 max-w-[1100px] text-[clamp(3.7rem,9.2vw,9.4rem)] font-bold leading-[.86] tracking-[-.09em]">{copy.hero[0]}<br/>{copy.hero[1]}<br/><em className="font-serif font-normal">{copy.hero[2]}</em></h1><div className="relative z-10 flex flex-col gap-7 sm:flex-row sm:items-end sm:gap-16"><p className="max-w-sm text-[17px] leading-[1.35]">{copy.lead}</p><div><a href="#demo" className="inline-flex items-center gap-7 bg-[#2864ff] px-5 py-4 text-[13px] font-bold text-white">{copy.demo} ↓</a><a href="#contact" className="ml-5 text-[13px] font-bold">{copy.contact} <ArrowUpRight className="inline h-4 w-4 text-[#2864ff]"/></a></div></div><div className="absolute right-[-7vw] top-[12vh] h-[35vw] w-[35vw] rounded-full bg-[radial-gradient(circle_at_35%_35%,#9bc0ff,#2864ff_46%,#0a309b_76%)] animate-[pulse_7s_ease-in-out_infinite]"/><div className="absolute bottom-[8vh] right-[24vw] h-[10vw] w-[10vw] rounded-full bg-[#2864ff] blur-sm"/></section>
    <section className="grid gap-8 border-t border-[#071120]/15 px-[4.5vw] py-28 lg:grid-cols-[1fr_2fr_1fr]"><p className="font-mono text-[11px] font-bold">[ 01 — EL PROBLEMA ]</p><h2 className="text-[clamp(2.8rem,5.4vw,5.8rem)] font-bold leading-[.92] tracking-[-.075em]">{copy.problem}</h2><p className="self-end text-base leading-relaxed">{copy.problemCopy}</p></section>
    <section id="demo" className="grid gap-12 bg-[#071120] px-[7vw] py-28 text-[#f4f4f0] lg:grid-cols-[1fr_430px] lg:items-center"><div><p className="font-mono text-[11px] font-bold tracking-wider">[ 02 — VERLO EN ACCIÓN ]</p><h2 className="mt-12 text-[clamp(2.8rem,5.3vw,5.6rem)] font-bold leading-[.92] tracking-[-.075em]">Rápida como para sentirse humana. Precisa como para escalar.</h2><p className="mt-6 max-w-md leading-relaxed text-white/65">Elige un canal. La conversación cambia. El cliente avanza sin esperar respuesta.</p><div className="mt-8 flex gap-2">{labels.map((x)=><button key={x} onClick={()=>setChannel(x)} className={`border px-3 py-2 text-xs ${channel===x?"border-white bg-white text-[#071120]":"border-white/30 text-white/70"}`}>{x}</button>)}</div></div><div className="rounded-[32px] border-[5px] border-[#263448] bg-[#eef1f5] p-4 text-[#071120] shadow-[16px_18px_0_#2864ff]"><div className="flex items-center gap-3 border-b border-[#ccd3db] pb-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#2864ff] font-bold text-white">Q</span><div><p className="text-xs font-bold">QubeSight concierge</p><p className="text-[10px] text-slate-500">{channel} · online now</p></div></div><div className="flex h-[330px] flex-col justify-end gap-3 py-5">{chats[active].map((x,i)=><div key={x} className={`max-w-[82%] rounded-xl px-3 py-2 text-xs leading-relaxed ${i%2?"ml-auto bg-[#2864ff] text-white":"bg-slate-200"}`}>{x}</div>)}</div><div className="border border-slate-300 bg-white p-3 text-xs text-slate-400">{es?"Escribe un mensaje":"Write a message"} <span className="float-right text-[#2864ff]">➤</span></div></div></section>
    <section className="min-h-[150vh] bg-[#071120] text-white"><div className="sticky top-0 flex min-h-screen items-center overflow-hidden px-[7vw]"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(#ffffff20_1px,transparent_1px),linear-gradient(90deg,#ffffff20_1px,transparent_1px)] [background-size:72px_72px]"/><div className="relative grid w-full gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="font-mono text-[11px] font-bold">[ 03 — IA EN MOVIMIENTO ]</p><h2 className="mt-10 text-[clamp(3rem,6.2vw,6.6rem)] font-bold leading-[.9] tracking-[-.085em]">{copy.film[0]}<br/><em className="font-serif font-normal text-[#9fc2ff]">{copy.film[1]}</em></h2><p className="mt-7 max-w-md text-white/60">{copy.film[2]}</p></div><div className="rounded-[28px] border border-white/15 bg-[#0d1020]/90 p-5 shadow-[0_40px_100px_-30px_#2864ff] backdrop-blur-xl"><div className="mb-8 flex items-center justify-between border-b border-white/10 pb-4 text-xs"><span>qube•sight / live agent</span><span className="text-emerald-300">● connected</span></div>{[[MessageCircle,"01 / INCOMING","¿Tienen disponibilidad esta semana?"],[Phone,"02 / QUALIFIED","Consulta · Jueves por la tarde"],[CalendarDays,"03 / BOOKED","Jueves · 2:30 PM"]].map(([Icon,label,text],i)=>{const I=Icon as typeof MessageCircle;return <div key={String(label)} className={`mb-3 ml-auto max-w-[88%] rounded-2xl border p-4 ${i===2?"border-emerald-400/40 bg-emerald-400/10":"border-white/10 bg-white/5"}`}><p className="flex items-center gap-2 text-[9px] font-bold tracking-widest text-white/45"><I className="h-3 w-3"/>{String(label)}</p><p className="mt-3 text-sm font-medium">{String(text)}</p>{i===2&&<p className="mt-3 flex items-center gap-1 text-xs text-emerald-300"><Check className="h-3 w-3"/> {es?"Reserva confirmada":"Booking confirmed"}</p>}</div>})}</div></div></div></section>
    <section id="product" className="bg-[#dbe6ff] px-[4.5vw] py-28"><p className="font-mono text-[11px] font-bold">[ 04 — PRODUCTOS ]</p><div className="mt-16 grid border border-[#071120]/20 md:grid-cols-3">{copy.products.map(([title,body],i)=><article key={title} className="flex min-h-[310px] flex-col border-b border-[#071120]/20 p-8 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><span className="font-mono text-[11px] text-[#526071]">0{i+1}</span><h3 className="mt-14 text-4xl font-bold tracking-[-.07em]">{title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed">{body}</p><a href="#contact" className="mt-auto text-xs font-bold">{es?"Explorar capacidad":"Explore capability"} <ArrowUpRight className="inline h-4 w-4 text-[#2864ff]"/></a></article>)}</div></section>
    <section id="process" className="grid gap-12 px-[4.5vw] py-28 lg:grid-cols-[1fr_1.5fr]"><div><p className="font-mono text-[11px] font-bold">[ 05 — CÓMO FUNCIONA ]</p><h2 className="mt-12 text-[clamp(3rem,5.5vw,5.8rem)] font-bold leading-[.9] tracking-[-.08em]">{es?"De la primera señal al cliente agendado.":"From first signal to booked customer."}</h2></div><div>{copy.how.map((x,i)=><div className="grid grid-cols-[50px_1fr] gap-5 border-t border-[#071120]/20 py-6" key={x}><span className="font-mono text-xs">0{i+1}</span><div><h3 className="text-2xl font-bold tracking-[-.06em]">{x}</h3><p className="mt-2 max-w-sm text-sm leading-relaxed text-[#526071]">{i===0?(es?"Tu agente recibe la llamada, mensaje o formulario.":"Your agent receives the call, message, or form."):i===1?(es?"Identifica intención, responde y reúne lo que importa.":"It identifies intent, answers, and gathers what matters."):(es?"Agenda, califica, deriva y hace que el siguiente paso sea fácil.":"It books, qualifies, routes, and makes the next step easy.")}</p></div></div>)}</div></section>
    <section id="solutions" className="bg-[#2864ff] px-[4.5vw] py-28 text-white"><p className="font-mono text-[11px] font-bold">[ 06 — SOLUCIONES ]</p><h2 className="mt-12 text-[clamp(3rem,5.8vw,6rem)] font-bold leading-[.9] tracking-[-.08em]">{es?"Negocios diferentes.\nUna respuesta superior.":"Different businesses.\nOne higher standard of response."}</h2><div className="mt-16 border-t border-white/40">{copy.industries.map((x,i)=><a href="#contact" className="grid grid-cols-[60px_1fr_30px] items-center border-b border-white/40 py-5" key={x}><span className="font-mono text-xs">0{i+1}</span><strong className="text-[clamp(1.7rem,3.5vw,3.5rem)] tracking-[-.06em]">{x}</strong><ArrowUpRight className="h-5 w-5"/></a>)}</div></section>
    <section className="grid gap-12 px-[4.5vw] py-28 lg:grid-cols-[1fr_2fr]"><p className="font-mono text-[11px] font-bold">[ 07 — FAQ ]</p><div>{copy.faq.map(([q,a],i)=><article className="border-t border-[#071120]/20" key={q}><button onClick={()=>setOpen(open===i?-1:i)} className="flex w-full items-center justify-between py-6 text-left text-lg font-bold"><span>{q}</span><ChevronDown className={`h-5 w-5 transition-transform ${open===i?"rotate-180":""}`}/></button>{open===i&&<p className="mb-7 max-w-xl text-sm leading-relaxed text-[#526071]">{a}</p>}</article>)}</div></section>
    <section id="contact" className="bg-[#071120] px-[4.5vw] py-28 text-[#f4f4f0]"><p className="font-mono text-[11px] font-bold">[ 08 — HABLEMOS ]</p><h2 className="mt-14 text-[clamp(3.3rem,7vw,7.8rem)] font-bold leading-[.88] tracking-[-.09em]">{copy.final}</h2><a className="mt-12 inline-flex items-center gap-8 bg-[#f4f4f0] px-5 py-4 text-sm font-bold text-[#071120]" href="https://wa.me/50646009140" target="_blank" rel="noreferrer">{copy.contact} <ArrowUpRight className="h-5 w-5"/></a></section>
    <footer className="flex flex-wrap justify-between gap-5 border-t border-white/15 bg-[#071120] px-[4.5vw] py-7 text-xs text-white/60"><span className="font-black tracking-[-.08em] text-white">qube<span className="text-[#2864ff]">•</span>sight</span><span>AI that moves business forward.</span><span>© 2026 QubeSight</span></footer>
  </main>;
};
export default QubeSightEditorialHome;
