import type { Agent } from "@/types/dashboard";

export const emptyAgent: Agent = {
  id: "",
  agent_type: null,
  business_name: "",
  business_description: "",
  assistant_description: "",
  configuration_status: "draft",
  capabilities: {},
  behavior: {},
  lead_fields: [],
  escalation_rules: {},
  published_at: null,
  name: "",
  status: "inactive",
  twilio_phone: "",
  voice_name: "Sofia",
  language: "Español",
  objective: "",
  greeting: "",
  system_prompt: "",
  deployment_revision: 1,
  deployed_revision: null,
  provisioning_status: "not_deployed",
  runtime_service: null,
  runtime_url: null,
  last_health_at: null,
  last_deployed_at: null,
  last_provisioning_error: null,
};
